-- Generated by Noctalia

local primary = "rgb(b4bcc4)"
local surface = "rgb(1a1d21)"
local secondary = "rgb(b4c4bc)"
local error = "rgb(cdacac)"

hl.config({
	general = {
		col = {
			active_border = primary,
			inactive_border = surface,
		},
	},

	group = {
		col = {
			border_active = secondary,
			border_inactive = surface,
			border_locked_active = error,
			border_locked_inactive = surface,
		},

		groupbar = {
			col = {
				active = secondary,
				inactive = surface,
				locked_active = error,
				locked_inactive = surface,
			},
		},
	},
})
