# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."n8n-n8n" = {
    image = "docker.n8n.io/n8nio/n8n";
    environment = {
      "GENERIC_TIMEZONE" = "America/New_York";
      "N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS" = "true";
      "N8N_HOST" = "n8n.codybense.com";
      "N8N_PORT" = "5678";
      "N8N_PROTOCOL" = "https";
      "N8N_RESTRICT_FILE_ACCESS_TO" = "/files";
      "NODE_ENV" = "production";
      "TZ" = "America/New_York";
      "WEBHOOK_URL" = "https://n8n.codybense.com/";
    };
    volumes = [
      "/home/cody/nix-config/modules/server/n8n/local-files:/files:rw"
      "n8n_n8n_data:/home/node/.n8n:rw"
    ];
    ports = [
      "127.0.0.1:5678:5678/tcp"
    ];
    labels = {
      "traefik.enable" = "true";
      "traefik.http.middlewares.n8n.headers.SSLHost" = "codybense.com";
      "traefik.http.middlewares.n8n.headers.SSLRedirect" = "true";
      "traefik.http.middlewares.n8n.headers.STSIncludeSubdomains" = "true";
      "traefik.http.middlewares.n8n.headers.STSPreload" = "true";
      "traefik.http.middlewares.n8n.headers.STSSeconds" = "315360000";
      "traefik.http.middlewares.n8n.headers.browserXSSFilter" = "true";
      "traefik.http.middlewares.n8n.headers.contentTypeNosniff" = "true";
      "traefik.http.middlewares.n8n.headers.forceSTSHeader" = "true";
      "traefik.http.routers.n8n.entrypoints" = "web,websecure";
      "traefik.http.routers.n8n.middlewares" = "n8n@docker";
      "traefik.http.routers.n8n.rule" = "Host(`n8n.codybense.com`)";
      "traefik.http.routers.n8n.tls" = "true";
      "traefik.http.routers.n8n.tls.certresolver" = "mytlschallenge";
    };
    log-driver = "journald";
    extraOptions = [
      "--network-alias=n8n"
      "--network=n8n_default"
    ];
  };
  systemd.services."docker-n8n-n8n" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-n8n_default.service"
      "docker-volume-n8n_n8n_data.service"
    ];
    requires = [
      "docker-network-n8n_default.service"
      "docker-volume-n8n_n8n_data.service"
    ];
    partOf = [
      "docker-compose-n8n-root.target"
    ];
    wantedBy = [
      "docker-compose-n8n-root.target"
    ];
  };
  virtualisation.oci-containers.containers."n8n-traefik" = {
    image = "traefik";
    volumes = [
      "/var/run/docker.sock:/var/run/docker.sock:ro"
      "n8n_traefik_data:/letsencrypt:rw"
    ];
    ports = [
      "80:80/tcp"
      "443:443/tcp"
    ];
    cmd = [ "--api.insecure=true" "--providers.docker=true" "--providers.docker.exposedbydefault=false" "--entrypoints.web.address=:80" "--entrypoints.web.http.redirections.entryPoint.to=websecure" "--entrypoints.web.http.redirections.entrypoint.scheme=https" "--entrypoints.websecure.address=:443" "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true" "--certificatesresolvers.mytlschallenge.acme.email=codybense@gmail.com" "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=traefik"
      "--network=n8n_default"
    ];
  };
  systemd.services."docker-n8n-traefik" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-n8n_default.service"
      "docker-volume-n8n_traefik_data.service"
    ];
    requires = [
      "docker-network-n8n_default.service"
      "docker-volume-n8n_traefik_data.service"
    ];
    partOf = [
      "docker-compose-n8n-root.target"
    ];
    wantedBy = [
      "docker-compose-n8n-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-n8n_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f n8n_default";
    };
    script = ''
      docker network inspect n8n_default || docker network create n8n_default
    '';
    partOf = [ "docker-compose-n8n-root.target" ];
    wantedBy = [ "docker-compose-n8n-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-n8n_n8n_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect n8n_n8n_data || docker volume create n8n_n8n_data
    '';
    partOf = [ "docker-compose-n8n-root.target" ];
    wantedBy = [ "docker-compose-n8n-root.target" ];
  };
  systemd.services."docker-volume-n8n_traefik_data" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      docker volume inspect n8n_traefik_data || docker volume create n8n_traefik_data
    '';
    partOf = [ "docker-compose-n8n-root.target" ];
    wantedBy = [ "docker-compose-n8n-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-n8n-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
