#!/usr/bin/env bash

PROJECTNAME=
PARENTDIR=
PARETNDIRCHOICE=
LANGUAGECHOICE=

mkpdir() {
    mkdir "$PARENTDIR"/"$PROJECTNAME"
}

createdKittySession() {
    printf "layout tall\nnew_tab terminal\nlaunch bash\ncd %s/%s\nnew_tab yazi\ncd %s/%s\nlaunch yazi\n" "$PARENTDIR" "$PROJECTNAME" "$PARENTDIR" "$PROJECTNAME" >"$PARENTDIR"/"$PROJECTNAME"/launch.kitty-session
}

launchProject() {
    kitty --session "$PARENTDIR"/"$PROJECTNAME"/launch.kitty-session &
    emacsclient "$PARENTDIR"/"$PROJECTNAME" &
}

createProject() {
    case $LANGUAGECHOICE in
    rust)
        echo '{{ Color "99" " Creating a rust project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        cd "$PARENTDIR" || exit
        cargo new "$PROJECTNAME"
        createdKittySession
        ;;
    go)
        echo '{{ Color "99" " Creating a rust project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        mkpdir "$PARENTDIR" "$PROJECTNAME"
        cd "$PARENTDIR"/"$PROJECTNAME" || exit
        go mod init "$PROJECTNAME"
        git init
        cat ~/nix-config/dotfiles/git/Go.gitignore >"$PARENTDIR"/"$PROJECTNAME"/.gitignore
        createdKittySession
        ;;
    zig)
        echo '{{ Color "99" " Creating a rust project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        mkpdir "$PARENTDIR" "$PROJECTNAME"
        cd "$PARENTDIR"/"$PROJECTNAME" || exit
        zig init
        git init
        cat ~/nix-config/dotfiles/git/Zig.gitignore >"$PARENTDIR"/"$PROJECTNAME"/.gitignore
        createdKittySession
        ;;
    python)
        echo '{{ Color "99" " Creating a rust project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        cd "$PARENTDIR" || exit
        uv init "$PROJECTNAME"
        createdKittySession
        ;;
    bash)
        echo '{{ Color "99" " Creating a bash project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        mkpdir "$PARENTDIR" "$PROJECTNAME"
        cd "$PARENTDIR"/"$PROJECTNAME" || exit
        git init
        touch "$PROJECTNAME"
        printf "#!/usr/bin/env bash\n\n" >"$PROJECTNAME"
        chmod +x "$PROJECTNAME"

        createdKittySession
        ;;
    *)
        echo '{{ Color "99" " Creating a project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$PARENTDIR" "$PROJECTNAME" | gum format -t template
        echo

        mkpdir "$PARENTDIR" "$PROJECTNAME"
        cd "$PARENTDIR"/"$PROJECTNAME" || exit
        git init
        cat ~/nix-config/dotfiles/git/C.gitignore >"$PARENTDIR"/"$PROJECTNAME"/.gitignore
        createdKittySession
        ;;
    esac
}

main() {
    gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 50 --margin "1 2" --padding "2 4" \
        'Create a new project'

    PROJECTNAME=$(gum input --placeholder "Project Name")
    PARETNDIRCHOICE=$(gum choose github projects)

    case $PARETNDIRCHOICE in
    github)
        PARENTDIR=$HOME/workspaces/github/CodyBense
        ;;
    *)
        PARENTDIR=$HOME/workspaces/projects
        ;;
    esac

    LANGUAGECHOICE=$(gum choose go rust zig c python bash)

    createProject "$LANGUAGECHOICE"

    echo '{{ Color "99" " Do you want to launch the project "}}' | gum format -t template
    sleep 1
    gum confirm && launchProject || exit
}

main
