#!/usr/bin/env bash

mkpdir() {
    mkdir -p "$1"/"$2"
}

launchProject() {
    local parentDir="$1"
    local projectName="$2"

    kitty --title "$projectName" --session "$HOME"/nix-config/dotfiles/kitty/sessions/project.kitty-session -d "$parentDir"/"$projectName" &
    sleep 0.5
    emacsclient -n "$parentDir"/"$projectName"
}

projectCreate() {
    local language="$1"
    local parentDir="$2"
    local projectName="$3"

    case "$language" in
    # go rust zig c python bash
    go)
        echo '{{ Color "99" " Creating a go project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        mkpdir "$parentDir" "$projectName"
        cd "$parentDir"/"$projectName" || exit
        go mod init github.com/CodyBense/"$projectName"
        git init
        cat ~/nix-config/dotfiles/git/Go.gitignore >"$parentDir"/"$projectName"/.gitignore
        ;;
    rust)
        echo '{{ Color "99" " Creating a rust project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        cargo new "$parentDir"/"$projectName"
        ;;
    zig)
        echo '{{ Color "99" " Creating a zig project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        mkpdir "$parentDir" "$projectName"
        cd "$parentDir"/"$projectName" || exit
        zig init
        git init
        cat ~/nix-config/dotfiles/git/Zig.gitignore >"$parentDir"/"$projectName"/.gitignore
        ;;
    python)
        echo '{{ Color "99" " Creating a python project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        uv init "$parentDir"/"$projectName"
        ;;
    bash)
        echo '{{ Color "99" " Creating a bash project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        mkpdir "$parentDir" "$projectName"
        cd "$parentDir"/"$projectName" || exit
        git init
        cat ~/nix-config/dotfiles/git/Shell.gitignore >"$parentDir"/"$projectName"/.gitignore
        printf "#!/usr/bin/env bash\n\n" >"$projectName"
        chmod +x "$projectName"
        ;;
    *)
        echo '{{ Color "99" " Creating a project "}}' | gum format -t template
        echo
        printf '{{ Color "99" " Creating project @ %s/%s "}}' "$parentDir" "$projectName" | gum format -t template
        echo
        mkpdir "$parentDir" "$projectName"
        cd "$parentDir"/"$projectName" || exit
        git init
        cat ~/nix-config/dotfiles/git/C.gitignore >"$parentDir"/"$projectName"/.gitignore
        ;;
    esac
}

main() {
    gum style \
        --foreground 212 --border-foreground 212 --border double \
        --align center --width 50 --margin "1 2" --padding "2 4" \
        'Create a new project'

    local projectName
    projectName=$(gum input --placeholder "Project Name")
    [[ -z "$projectName" ]] && exit 1

    local parentDirChoice
    parentDirChoice=$(gum choose github projects)

    local parentDir
    case "$parentDirChoice" in
    github)
        paretDir="$HOME"/workspaces/github/CodyBense
        ;;
    *)
        paretDir="$HOME"/workspaces/projects
        ;;
    esac

    local languageChoice
    languageChoice=$(gum choose go rust zig c python bash)

    projectCreate "$languageChoice" "$paretDir" "$projectName"

    echo '{{ Color "99" " Do you want to launch the project "}}' | gum format -t template
    sleep 1
    # gum confirm && launchProject "$parentdir" "$projectname" || exit
    if gum confirm; then
        launchProject "$parentDir" "$projectName"
    fi
}

main
